### ISSUE TITLE
No module named 'skfmm.cfmm'

### ISSUE THREAD

**Issue by sdadsadsfwqcxzcx** [scikit-fmm/scikit-fmm#21]
how to solve this problem?

**Comment by jkfurtney** [comment]
This error happens when scikit-fmm cannot find the internal c extension module. Often this happens when people compile/install scikit-fmm and then try to run the tests in the source directory. If you compiled and installed from source try to cd to another directory and try again. Otherwise the c extension module did not build correctly. In this case could you post the output of `python setup.py build`.

Thanks,
Jason
