### ISSUE TITLE
distance calculations with point source

### ISSUE THREAD

**Issue by d-chambers** [scikit-fmm/scikit-fmm#47]
Hi,

I am trying to simulate a point source in a 2D homogeneous media but I am getting some unexpected results for distances compared with the analytical solution. I am using skfmm version 2019.1.30, python 3.7, and ubuntu 18.04.

A simple example:

```python
import numpy as np
import skfmm

phi = np.ones([5, 5])
phi[0, 0] = 0  # set point source at origin

dx  = 1

dist = skfmm.distance(phi=phi, dx=dx)
```

The cells in the vertical and horizontal direction give me the expected answers:

```python
assert np.all(dist[:, 0] == np.array([0, 1, 2, 3, 4]))
assert np.all(dist[0, :] == np.array([0, 1, 2, 3, 4]))
```

But the diagonal cells do not match the straight line distance from the center of the zero-contour cell:

```python
print(np.diag(dist))  # array([0.        , 1.70710678, 3.15737528, 4.55895359, 5.95627062])
expected = np.sqrt(((np.arange(5) * dx) **2) * 2)  # array([0.        , 1.41421356, 2.82842712, 4.24264069, 5.65685425])
```

Is this the correct way to represent a point source?

**Comment by jkfurtney** [comment]
Hi Derrick,

Thanks for getting in touch and for your interest in this module. You have it right, there is no way to represent exactly a point source, it has to be discretized into cells. The solution given by skfmm.distance() is different than the exact solution because linear interpolation is used to reconstruct the zero-contour of phi during the model initialization. Also the error is the worst along the diagonal directions because the computational stencil is aligned with the coordinate directions. These error should decrease as you increase the resolution. 

I hope that makes sense and helps you out. I will close this issue for now, but if there are other problem you can reopen it.

**Comment by d-chambers** [comment]
Thanks @jkfurtney for the quick response and for your work on this library. I guess there is nothing to do but be aware of this error. 

In case it is useful for someone else I thought I would share a quick plot of the % deviation from the analytical solution for the diagonal cells. It goes from ~20% in the diagonal block next to the "source" to ~ %0.15 in cell 100, 100.

![image](https://user-images.githubusercontent.com/11671536/97502891-46644380-1931-11eb-9f1e-62dc567c86d0.png)

**Comment by jkfurtney** [comment]
Thanks for providing this plot. Another thing to consider: although the method is second-order, the initialization of the narrow-band is first-order (liner interpolation). These first-order errors are propagated and are particularly bad along the diagonals. I started a branch that uses cubic interpolation to construct the narrow-band, the convergence and accuracy are better. The branch is  https://github.com/scikit-fmm/scikit-fmm/tree/new-init 

It is working for simple cases, but is behind the current master. It has been on my list to get this into master. It requires SciPy so I have been hesitant to merge it. It may be best to have the cubic initialization as an option that defaults to off (so that SciPy is a soft requirement).

**Comment by d-chambers** [comment]
Thanks, I will generate that same plot with the branch you mention when I find a few minutes. 

> It requires SciPy so I have been hesitant to merge it.

I may not share the prospective of all of the scikit-fmm users, but requiring SciPy to run a "scikit-something" seems absolutely reasonable, even expected. The [scikit documentation](https://www.scipy.org/scikits.html) even describes scikits as "add-on packages for SciPy"
