### ISSUE TITLE
Conceptual: Description of the chosen boundary curve

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [scikit-fmm/scikit-fmm#56]
Hi! I'm trying to understand the boundary curve of the algorithm used. 

I've made a few plots:

![image](https://user-images.githubusercontent.com/33344633/127245708-09a2845e-b1e7-455e-b003-cfd5bfdcd6d4.png)

![image](https://user-images.githubusercontent.com/33344633/127245723-abe73412-807f-4b8c-bb30-2a987e6f6047.png)

For the first plot, since there is no white area, it seems that there's no space for any putative boundary to live (which in turn suggests that the algorithms is buggy)

For the second plot, it looks like this configuration might actually be feasible, in that there exists a curve that never enters any grey area and touches all the black circles at least once (it'd have to essentially follow the "extremal points" of the white area), but it's a rather awkward boundary to choose. 

How would you describe the chosen boundary curve?

**Comment by jkfurtney** [comment]
Hi and thanks for getting in touch. I am unclear what you are asking. Could you describe the big picture of what you are trying to do and maybe I can help? If you have found a bug could you provide a code example that shows the problem and a description of what the problem is?

In general, this is implicit surface representation where the surface or boundary is the zero contour of a function in one dimension higher. In scikit-fmm specifically, the function is just an array of numbers and the surface or boundary is the zero contour. In a sense the surface exists at any boundary between adjacent cells where the sign is opposite or in cells where the value is exactly zero. Also you can reconstruct the surface by using linear or quadratic interpolation over the cells.

**Comment by kevin-thankyou-lin** [comment]
Hi, thanks for getting back to me. I'm using fmm to go shortest collision free path planning - this seems to work decently from observing the path generated using gradient descent.

Maybe I can be more specific with my question:

What exactly do the distances in the corner entries of the following 3 x 3 grid with a -1 in the centre represent?

![image](https://user-images.githubusercontent.com/33344633/127785256-0a90c5bc-c577-4cec-b535-cdcb858c725a.png)

At first, I was thinking the distance values represented distances from the $$phi=0$$ contour. In the example above, I was thinking this contour was the diamond shape with corners (0, \pm 0.5), (\pm 0.5, 0). However, the corner numbers have to be ~1.06 if the contour was indeed the diamond. So, I'm not sure what the distances represent.

**Comment by jkfurtney** [comment]
In general the values represent the smallest distance from the cell center to the zero contour of phi.

In this example, the values in the central, north, south, east, and west cells are determined from a linear reconstruction of phi. The code for this is in the function `distanceMarcher::initalizeFrozen()`. The corner points are determined by the point updating scheme of the fast marching method. An upwind finite difference approximation of the distance function gradient is made based on the distance at known (frozen) points. Because of the way the FD stencil is oriented, there are some errors along the diagonal in cases like this.  I hope that helps to clarify, a good reference is James Sethian's text book: "Level Set Methods and Fast Marching Methods: Evolving Interfaces in Computational Geometry, Fluid Mechanics, Computer Vision, and Materials Science"

**Comment by kevin-thankyou-lin** [comment]
Got it - yup, Prof. Sethian was my Multi-variable Calculus professor back in the good old days :)

To help others understand the example, I think it'd be good to add to the documentation that the error in the diagonal entries is expected. That'd help save some time trying to figure out things! Thanks, nevertheless!
